"""initial migration

Revision ID: 64fe74647a83
Revises: d7056a88e980
Create Date: 2018-02-15 19:57:05.988555

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '64fe74647a83'
down_revision = 'd7056a88e980'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_me', sa.Text(), nullable=True))
    op.drop_column('users', 'about')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about', mysql.TEXT(collation=u'utf8_bin'), nullable=True))
    op.drop_column('users', 'about_me')
    # ### end Alembic commands ###
